name: CI/CD Produção (main)

on:
  push:
    branches:
      - main # Executa somente em pushes na branch principal

jobs:
  # 🧪 1️⃣ Etapa de Testes Unitários
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Faz checkout do código
      - name: Checkout código fonte
        uses: actions/checkout@v4

      # 2️⃣ Instala Node.js e dependências
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci

      # 3️⃣ Executa os testes unitários
      #- name: Executar testes unitários
      #run: npm test -- --watch=false --browsers=ChromeHeadless

  # 🧱 3️⃣ Etapa de Build e Deploy com Docker + Render
  build-and-deploy:
    name: Build Angular & Deploy to Render (Produção)
    runs-on: ubuntu-latest
    needs: [test] # só executa se os testes passarem

    steps:
      # 1️⃣ Faz checkout do código
      - name: Checkout código fonte
        uses: actions/checkout@v4

      # 2️⃣ Instala Node e dependências
      - name: Instalar Node.js e dependências
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci

      # 3️⃣ Build Angular usando o environment de produção
      - name: Testar build do Angular (production)
        run: npm run build

      # 4️⃣ Valida o Dockerfile localmente
      - name: Validar Docker build (sem subir imagem)
        run: docker build -t angular-docker-test .

      # 5️⃣ Dispara o deploy no Render via Webhook (Produção)
      - name: Disparar deploy no Render (Produção)
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL_PROD }}"
