name: CI/CD Angular + Docker + Render

on:
  push:
    branches:
      - main # Executa somente em pushes na branch principal

jobs:
  # 🧪 1️⃣ Etapa de Testes Unitários
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código fonte
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes unitários
        run: npm test -- --watch=false --browsers=ChromeHeadless

  # 🔢 2️⃣ Etapa de Verificação de Versão
  version-check:
    name: Check Application Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código fonte
        uses: actions/checkout@v4

      - name: Verificar versão do package.json
        run: |
          git fetch origin main || true
          git show origin/main:package.json > last_package.json || echo '{}' > last_package.json
          CURRENT=$(jq -r '.version' package.json)
          LAST=$(jq -r '.version' last_package.json)
          if [ "$CURRENT" = "$LAST" ]; then
            echo "❌ A versão não mudou. Atualize o número no package.json (atual: $CURRENT)."
            exit 1
          fi
          if [ "$(printf '%s\n' "$LAST" "$CURRENT" | sort -V | head -n1)" = "$CURRENT" ]; then
            echo "❌ Versão atual ($CURRENT) não é maior que a anterior ($LAST)."
            exit 1
          fi
          echo "✅ Versão válida: $CURRENT > $LAST"

  # 🧱 3️⃣ Etapa de Build e Deploy com Docker + Render
  build-and-deploy:
    name: Build Angular & Deploy to Render
    runs-on: ubuntu-latest
    needs: [test, version-check] # só executa se os anteriores passarem

    steps:
      # 1️⃣ Faz checkout do código
      - name: Checkout código fonte
        uses: actions/checkout@v4

      # 2️⃣ Instala Node e dependências
      - name: Instalar Node.js e dependências
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci

      # 3️⃣ Testa o build do Angular (garante que compila)
      - name: Testar build do Angular
        run: npm run build

      # 4️⃣ Valida o Dockerfile localmente
      - name: Validar Docker build (sem subir imagem)
        run: docker build -t angular-docker-test .

      # 5️⃣ Dispara o deploy no Render via Webhook
      - name: Disparar deploy no Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
