name: CI/CD Desenvolvimento (develop)

on:
  push:
    branches:
      - develop # Executa somente em pushes na branch develop

jobs:
  # 🧪 1️⃣ Etapa de Testes Unitários
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Faz checkout do código fonte
      - name: Checkout código fonte
        uses: actions/checkout@v4

      # 2️⃣ Instala Node.js e dependências
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci

      # 3️⃣ Executa os testes unitários
      #- name: Executar testes unitários
      #run: npm test -- --watch=false --browsers=ChromeHeadless

  # 🧱 3️⃣ Etapa de Build e Deploy com Docker + Render
  build-and-deploy:
    name: Build Angular & Deploy to Render (Desenvolvimento)
    runs-on: ubuntu-latest
    needs: [test] # só executa se os testes passarem

    steps:
      # 1️⃣ Faz checkout do código fonte
      - name: Checkout código fonte
        uses: actions/checkout@v4

      # 2️⃣ Instala Node.js e dependências
      - name: Instalar Node.js e dependências
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci

      # 3️⃣ Realiza build Angular usando o environment 'dvp'
      - name: Executar build do Angular (dvp)
        run: npm run build -- --configuration=dvp

      # 4️⃣ Valida o Dockerfile localmente
      - name: Validar Docker build (sem subir imagem)
        run: docker build -t angular-docker-test .

      # 5️⃣ Dispara o deploy no Render (Desenvolvimento)
      - name: Disparar deploy no Render (Desenvolvimento)
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL_DEV }}"
